# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testempty' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testempty' do
    @driver.get('http://127.0.0.1:3000/')
    @driver.manage.resize_to(924, 1053)
    @driver.find_element(:name, 'commit').click
  end
end
